/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class github_elroy93_jvmlocals_JvmLocals */

#ifndef _Included_github_elroy93_jvmlocals_JvmLocals
#define _Included_github_elroy93_jvmlocals_JvmLocals
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     github_elroy93_jvmlocals_JvmLocals
 * Method:    getLocals
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_github_elroy93_jvmlocals_JvmLocals_getLocals
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
